apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: ct-govex-app   # Name of the resource
spec:
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 80
    targetPort: 4813
  selector:
    app: ct-govex-app         # Map any pod with label `app=go-hello-world` to this service
  type: NodePort
