apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  creationTimestamp: "2020-07-04T20:22:57Z"
  labels:
    app: ct-govex-app
  name: ct-govex-app           # Name of the Kubernetes resource
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: ct-govex-app        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: ct-govex-app 
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: ct-govex-app
        image: aarryann/govex:ct-govex-app 
        imagePullPolicy: IfNotPresent
        command: ["node", "__sapper__/build"]
        env:
        - name: PATH
          value: /opt/rh/rh-nodejs12/root/usr/bin:/opt/app-root/src/node_modules/.bin/:/opt/app-root/src/.npm-global/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TERM
          value: xterm
        - name: HOSTNAME
        - name: container
          value: podman
        - name: SUMMARY
          value: Platform for building and running Node.js 12 applications
        - name: STI_SCRIPTS_PATH
          value: /usr/libexec/s2i
        - name: PLATFORM
          value: el7
        - name: ENV
          value: /opt/app-root/etc/scl_enable
        - name: HOME
          value: /opt/app-root/src
        - name: NODEJS_SCL
          value: rh-nodejs10
        - name: NODEJS_VERSION
          value: "12"
        - name: MANPATH
          value: /opt/rh/rh-nodejs12/root/usr/share/man
        - name: NODE_ENV
          value: development
        - name: DESCRIPTION
          value: Node.js 12 available as container is a base platform for building and
            running various Node.js 12 applications and frameworks. Node.js is a platform
            built on Chrome's JavaScript runtime for easily building fast, scalable network
            applications. Node.js uses an event-driven, non-blocking I/O model that makes
            it lightweight and efficient, perfect for data-intensive real-time applications
            that run across distributed devices.
        - name: PROMPT_COMMAND
          value: . /opt/app-root/etc/scl_enable
        - name: NPM_RUN
          value: start
        - name: X_SCLS
          value: rh-nodejs12
        - name: MODE_ENV
          value: local
        - name: APP_ROOT
          value: /opt/app-root
        - name: BASH_ENV
          value: /opt/app-root/etc/scl_enable
        - name: NAME
          value: nodejs
        - name: NPM_CONFIG_PREFIX
          value: /opt/app-root/src/.npm-global
        - name: LD_LIBRARY_PATH
          value: /opt/rh/rh-nodejs12/root/usr/lib64
        - name: PORT
          value: "4813"
        - name: STI_SCRIPTS_URL
          value: image:///usr/libexec/s2i
        ports:
        - containerPort: 4813  # Should match the port number that the Go application listens on
          protocol: TCP
        workingDir: /app

